# Generated by Django 5.1.5 on 2025-01-30 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='The course name must be unique.', max_length=255, unique=True)),
                ('total_hour', models.PositiveIntegerField()),
                ('student', models.ManyToManyField(related_name='courses', to='accounts.student')),
                ('teacher', models.ManyToManyField(related_name='courses', to='accounts.teacher')),
            ],
            options={
                'db_table': 'Course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='subject.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='contents/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='subject.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(choices=[('HT', 'History'), ('MT', 'Math'), ('SC', 'Science')], max_length=2)),
            ],
            options={
                'db_table': 'Subject',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='Subject_title_753d14_idx'), models.Index(fields=['-created_at'], name='Subject_created_ebe166_idx')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='subject.subject'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title', 'created_at'], name='Course_title_70654c_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_course_name'),
        ),
    ]
