# Generated by Django 5.1.5 on 2025-01-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
